clone:
	if ! [ -d samba ];then git clone https://gitlab.com/samba-team/devel/samba.git; fi
	if ! [ -d sit-test-cases ];then git clone https://github.com/samba-in-kubernetes/sit-test-cases.git; fi
	if ! [ -d ceph ];then git clone https://github.com/ceph/ceph.git; fi
